config/routes.rb
Rails.application.routes.draw do

  delete 'logout' => 'login#destroy'

  get 'logins/new'

  get 'logins/create'

  get 'logins/destroy'
  

  resource :login, :only => [:new, :create, :destroy] do
    get 'logins/destroy' => 'login#destroy'
  end
  resources :users, :only => [:new,:create]
  resources :problems, :only => [:index,:new,:create,:show] do
    delete '/resolve' => 'problems#resolve'
    resources :notes, :only => [:new,:create]
  end
  
  root 'problems#index'

end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :user
  belongs_to :problem

  validates :text, presence: true
  validates :user, presence: true
  validates :problem, presence: true

end

app/models/problem.rb
class Problem < ActiveRecord::Base
  belongs_to :user
  has_many :notes

  validates :text, presence: true
  validates :tried, presence: true
  validates :user, presence: true
  
  def resolved?
    problems.where(resolved: true)
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :notes
  has_many :problems

  validates :email,
            presence: true,
            uniqueness: { case_sensitive: false },
            format: { with: /\A[\w\-\.]+@[\w\-\.]+\Z/, message: "must be a valid email address" }

  validates :name, presence: true

  has_secure_password
  
  def to_s
    name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?
  before_action :current_user

  private

  def current_user
    @current_user ||= User.find_by(id: session[:current_user_id])
  end

  def logged_in?
    current_user
  end

  def authenticate
    current_user_id = session[:current_user_id]
    unless current_user_id
      redirect_to new_login_path, notice: "You must be logged in to see that."
    end
    
  end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
      session[:current_user_id] = @user.id
      redirect_to root_path, notice: "You have successfully logged in."
    else
      flash.now[:error] = "You email or password was incorrect."
      render :new
    end
  end

  def destroy
    session[:current_user_id] = nil
    redirect_to root_path, notice: "You have been logged out."
  end
  
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :authenticate
  before_action :set_note, only: [:destroy, :update]


  def new
    @note = Note.new
  end

  def create
    @problem = Problem.find(params[:problem_id])
    @note = current_user.notes.build(note_params)
    @note.problem = @problem
    respond_to do |format|
      format.html do
        if @note.save
          redirect_to @problem
        else
          render "notes/show"
        end
      end

      format.js do
        if @note.save
          render :create, status: :created
        else
          render nothing: true, status: :bad_request
        end
      end
    end
  end
    # if @note.save && @note.user != @problem.user
    #   NoteMailer.new_note(@note.problem.user,@note).deliver
    #   redirect_to problem_path(@problem), notice: "You successfully submitted a note!"
    # else
    #   redirect_to problem_path(@problem), alert: "Sorry, you must enter a note. "
    # end
    # end


  private

  def set_note
		@note = Note.find(params[:id])
  end

  def note_params
    params.require(:note).permit(:text)
  end
end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
  # before_create :set_problem, only: [:show]

  def index
    @problems = Problem.order(created_at: :asc).paginate(page: params[:page], per_page: 5)
  end

  def new
    @problem = Problem.new
  end

  def create
    @problem = current_user.problems.build(problem_params)
    if @problem.save
      @user = current_user
      NewProblemMailer.new_problem(@problem.user,@problem).deliver
      redirect_to root_path, notice: "You successfully asked a question!"
    else
      redirect_to root_path, error: "You have to be logged in to do that"
    end
    ################ testing Javacript in controller
    respond_to do |format|
        format.html do
          if @problem.save
            return
          else
            render "problem/show"
          end
        end
      format.js do
        if @problem.update_attribute.save
          render "problem/create", status: :created
        else
          render "problem/create", status: :accepted
        end
      end
    end
  end

  def resolve
    @problem = Problem.find(params[:problem_id])
    if current_user && current_user.id == @problem.user.id
      @problem.update_attribute(:resolved, true)
    ##############  @problem.delete I'm going to comment this to not elimininated the problem and this one stays on ther webpage.
      redirect_to @problem, notice: "You've successfully resolved your problem."
    else
      redirect_to @problem, alert: "sorry, you can't do that."
    end
  end


  def show
    @problem = Problem.find(params[:id])
  end

  private

  def set_problem
    @problem = Problem.find(params[:id])
  end

  def problem_params
    params.require(:problem).permit(:text, :tried, :resolved)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:current_user_id] = @user.id
      redirect_to root_path, notice: "User was succesfully created."
    else
      render :new
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def display_alert(type = :notice)
    if flash[type]
      content_tag(:div, "data-alert" => "data-alert", :class => "alert-box #{type}") do
        flash[type]
      end
    end
  end
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/problems_helper.rb
module ProblemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HH</title>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  <link href='http://fonts.googleapis.com/css?family=Josefin+Sans' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=EB+Garamond' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag :defaults %>

  <%= csrf_meta_tags %>
</head>
<body>  
	<!-- <div class="icon-bar six-up"> -->
		<ul class="breadcrumbs">
		  <li><i class="fa fa-home fa-4x"></i>&nbsp<%= link_to "Home", root_path, :class => "topbar_links" %></li>
		
	  
		  <% if logged_in? %>
		  <li><i class="fa fa-question fa-4x"></i>&nbsp&nbsp<%= link_to 'New Problem', new_problem_path,:class => "topbar_links" %></li>
		  <li><i class="fa fa-sign-out fa-4x"></i>&nbsp<%= link_to "Logout", logins_destroy_path, :class => "topbar_links"%></li>
	  	  <% else %>
		  <li><i class="fa fa-plug fa-4x"></i>&nbsp<%= link_to "Login", new_login_path, :class => "topbar_links" %></li>
			  <li><i class="fa fa-pencil-square-o fa-4x"></i>&nbsp<%= link_to "Sign Up", new_user_path, :class => "topbar_links" %></li>
		
		  	  
	  <% end %>
	  <% if current_user %>
	  	<li> <i class="fa fa-user fa-4x"></i>&nbsp<%= link_to "Logged in as #{current_user}","#", {:class => "current"} %> </li>
		
		<% end %>
		
</ul>
	<!-- </div> -->
<!-- <ul class="breadcrumbs">
<li> <%= link_to 'Home', root_path, :class => "topbar_links" %></li>
<% if @current_user %>
	<li><%= link_to "Logged in as #{current_user}", "#", {:class => "current"} %></li>
	<li><%= link_to 'New Problem', new_problem_path, :class => "topbar_links"%></li>
	<li> <%= link_to 'Logout', logins_destroy_path,:class => "topbar_links" %></li>
<% else %>
	<li><%= link_to "Sign Up", new_user_path, :class => "topbar_links" %></li>
	<li><%= link_to "Login", new_login_path, :class => "topbar_links" %></li>
<% end %>

</ul> -->
  <%= display_alert(:notice) %>
  <%= display_alert(:alert) %>
<%= yield %>


</body>
</html>

app/views/logins/new.html.erb
<div class="row">
  <h1 class="large-12 columns">Login</h1>

  <%= form_tag login_path, :method => :post do %>
      <div class="large-6 columns">
        <%= label_tag :email %>
        <%= text_field_tag :email %>
      </div>
      <div class="large-6 columns">
        <%= label_tag :password %>
        <%= password_field_tag :password %>
      </div>
      <div class="large-12 columns">
        <%= button_tag "Login", :class => "small radius" %>
      </div>
  <% end %>
</div>

app/views/notes/_note.html.erb
<div class="row" id="<%= note.persisted? ? dom_id(note) : "note-new" %>">
    <div><%= note.text %></div>
    <div> Added by <%= note.user %>:</div>
</div>

app/views/notes/create.js.erb
$("#<%= dom_id(@noteable) %> .note").replaceWith("<%= j render(@note) %>");
$("#<%= dom_id(@noteable) %>").effect("highlight", {}, 1500);
// $("#notes").append("<%= j render(@note) %>");

app/views/problems/create.html.erb
<h1>Problems#create</h1>
<p>Find me in app/views/problems/create.html.erb</p>

app/views/problems/create.js.erb
$("#problems").append("<%= j render(@problems) %>");
$("#<%= dom_id(@problems) %>").effect("highlight", {}, 1500);

app/views/problems/index.html.erb
<div class="title">Homework Helper</div>
    <tbody>
		<% @problems.each do |problem| %>
            <div id="<%= dom_id(problem) %>">
			<div class="content">
            <tr>
				<p>Asked by <%= problem.user.to_s %>
				on <%= problem.created_at.strftime("%A, %B %d, %Y at %l:%M%P") %></p>
			<h5>Here's my problem:</h5>
			    <%= link_to truncate(problem.text, length: 40), problem_path(problem), :class => "problem" %>
			</tr>
            <% if problem.user == current_user %>
                <h5>Has your problem been resolved?</h5>
                <i class="fa fa-check fa-2x"></i><%= link_to 'Resolve', problem_resolve_path(problem.id),remote: true, method: :delete, data: { confirm: 'Are you sure?' }, :class => "resolve" %>
            <% end %>
            </div>
            </div>
        <% end %>
    </tbody>
<div class="paginate">
  <%= will_paginate @question %>
</div>
</div>

app/views/problems/new.html.erb
<%= simple_form_for @problem  do |form| %>
  <div class="row">
   <div class="title_2">What's your problem?</div>
  <div class="large-6 columns">
  <%= form.input :text,placeholder: "text" %>
  </div>
  <div class="large-6 columns">
  <%= form.input :tried, placeholder: "what I've tried so far" %>
  </div>
  <div class="row">
      <div class="large-12 columns">
      <%= form.button :submit, "Ask" %>
      </div>
  </div>
  </div>

<% end %>

app/views/problems/resolve.js.erb
$("#<%= dom_id(@problem) %>").detach();

app/views/problems/show.html.erb
<div class="probs"><h4><%= @problem.user.to_s %> has a problem:
	<div class="text"><h5><%= @problem.text %></h5></div>
	<h3>Here's what I've tried so far:</h3>
	<div class="text"><h5><%= @problem.tried %></h5></div>
	<br><br>
	<% if @problem.user == current_user %>
	Has your problem been resolved?
	<i class="fa fa-check fa-2x"></i><%= link_to 'Resolve', problem_resolve_path(@problem.id), method: :delete, :class => "resolve" %>
	<% end %>
	<h4><%= pluralize(@problem.notes.count, "Note") %></h4>
	<% @problem.notes.each do |note| %>
	<ul>
		Added by <%= note.user %>:
		<%= note.text %></ul>
		<br>
		<% end %>
		<h4>Add a note to <%= @problem.user.to_s %>'s problem:</h4>
		<%= form_for ([@problem, @problem.notes.build]) do |f| %>
		<div class="row">
			<div class="small-12 columns">
				<%= f.text_area :text, class: 'field_label' %><br>
				<div class="actions">
					<%= f.button :submit, class: "radius small" %> <br>
				</div>
			</div>
		</div>
		<% end %>
	</div>

app/views/users/new.html.erb
<div class="row">
  <h1 class="large-12 columns">Sign up</h1>
  <%= simple_form_for @user do |form| %>
      <div class="large-12 columns">
        <%= form.input :name %>
      </div>
      <div class="large-12 columns">
        <%= form.input :email %>
      </div>
      <div class="large-6 columns">
        <%= form.input :password %>
      </div>
      <div class="large-6 columns">
        <%= form.input :password_confirmation %>
      </div>
      <div class="large-12 columns">
        <%= form.button :submit, class: "radius small" %>
      </div>
  <% end %>
</div>